---
- name: Deploy Nginx Docker Container on Arch Linux
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure Docker is installed
      pacman:
        name: docker
        state: present

    - name: Ensure Docker service is started and enabled
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Ensure Python pip is installed
      pacman:
        name: python-pip
        state: present

    - name: Ensure Docker Python library is installed
      pip:
        name: docker
        state: present

    - name: Pull Nginx Docker image
      docker_image:
        name: nginx
        source: pull
        tag: latest

    - name: Run Nginx Docker container
      docker_container:
        name: nginx_container
        image: nginx:latest
        state: started
        ports:
          - "80:80"
